### ISSUE TITLE
Possible to support FLAC?

### ISSUE THREAD

**Issue by mikepspc** [dalecurtis/llama-demo#4]
Hi, 

Been trying to get FLAC playback working, however I'm stuck with extracting metadata.

Is it possible to get FLAC to work in this manner (gapless)?

**Comment by dalecurtis** [comment]
I'm not familiar with the details, but I'd be surprised if you had to do anything for FLAC. It's supposedly lossless, so the output signal should 100% match the input signal without need for any preroll/postroll trimming. What issues are you seeing?

(Closing since this isn't a issue with the demo, but happy to keep discussing)
